### PR TITLE
Update Typescript to 3.2.1 (#118)

### LINKED ISSUE #118: Can't start editor
I can't start the editor anymore, tested it with latest master and dev commits (30637183dbf14fbef9213166e629ada3cfb1ffcb , 780da19a5ac4176f8511e2f7799e8cbeaf5840a5)
image
image

The latest working commit for me is: 11d50c4cbac4d5772cf2ef9837d751cb1734b323 this means that this commit is breaking it for me: 3fedaabe6244890574545aed8532a76fff33ba2a

Setup:
Native install via npm on a Windows 10

### PR DESCRIPTION
**Pull request by Atyanar**
## Proposed Changes
  - Updates Typescript to 3.2.1
 

Fixes #118 (it wasn't really broken in the first place, since the typescript version marked in the repo was 3.1.6, but a lot of people seem to just be using latest typescript and this should fix the issue for them)

### CODE REVIEW

**Comment by Atyanar** [comment]
Let me check again, but according to the types those are not supported fields in the schema anymore

**Comment by Atyanar** [comment]
ah, nevermind, I will revert that part. The current types for slate export a faulty schema type, the Marks should still work, I guess

**Comment by adrianjost** [comment]
It's still not starting 😥
image

**Comment by FWirtz** [comment]
great, thanks for the update @adrianjost!

**Pull request merged**
